spring:
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
application:
  jwt:
    secretKey: RentyBackend;RentyBackend;RentyBackend;RentyBackend;RentyBackend;RentyBackend;RentyBackend;
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 1

stripe:
  key:
    secret: sk_test_51IMvgyJcxq1wroO7xkeNp1NPODEWPNShSLdEh53V2kXxXP60omIykZQM8fsUyw2tZvTRBWDYNXT7gE2gowWtjEuB00SJILj4nT
    public: pk_test_51IMvgyJcxq1wroO7RHpy6puCkeceDfydJfMw8xPK4554rQbL6Iz51iZ0rMIZ5PVD8esVbpVlDg0o6dKaeVWcPTg000CQB3zlt0